USE [master]
GO
/****** Object:  Database [gbt]    Script Date: 2/5/2021 12:28:29 AM ******/
CREATE DATABASE [gbt]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'gbt', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\gbt.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'gbt_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\gbt_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [gbt] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [gbt].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [gbt] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [gbt] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [gbt] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [gbt] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [gbt] SET ARITHABORT OFF 
GO
ALTER DATABASE [gbt] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [gbt] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [gbt] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [gbt] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [gbt] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [gbt] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [gbt] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [gbt] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [gbt] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [gbt] SET  DISABLE_BROKER 
GO
ALTER DATABASE [gbt] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [gbt] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [gbt] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [gbt] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [gbt] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [gbt] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [gbt] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [gbt] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [gbt] SET  MULTI_USER 
GO
ALTER DATABASE [gbt] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [gbt] SET DB_CHAINING OFF 
GO
ALTER DATABASE [gbt] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [gbt] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [gbt] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [gbt] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [gbt] SET QUERY_STORE = OFF
GO
USE [gbt]
GO
/****** Object:  Table [dbo].[payroll]    Script Date: 2/5/2021 12:28:29 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[payroll](
	[driverid] [nchar](10) NOT NULL,
	[salary] [nvarchar](50) NOT NULL,
	[expenses] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_payroll] PRIMARY KEY CLUSTERED 
(
	[driverid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[roster]    Script Date: 2/5/2021 12:28:29 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[roster](
	[driverid] [nchar](10) NOT NULL,
	[name] [varchar](50) NOT NULL,
	[truck] [varchar](50) NOT NULL,
 CONSTRAINT [PK_roster] PRIMARY KEY CLUSTERED 
(
	[driverid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[trip]    Script Date: 2/5/2021 12:28:29 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[trip](
	[driverid] [nchar](10) NOT NULL,
	[route] [nvarchar](50) NULL,
 CONSTRAINT [PK_trip] PRIMARY KEY CLUSTERED 
(
	[driverid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[roster]  WITH CHECK ADD  CONSTRAINT [FK_roster_roster] FOREIGN KEY([driverid])
REFERENCES [dbo].[roster] ([driverid])
GO
ALTER TABLE [dbo].[roster] CHECK CONSTRAINT [FK_roster_roster]
GO
USE [master]
GO
ALTER DATABASE [gbt] SET  READ_WRITE 
GO
